INSERT INTO paises (id,nombre) VALUES(1,'Afganistán');
INSERT INTO paises (id,nombre) VALUES(2,'Islas Gland');
INSERT INTO paises (id,nombre) VALUES(3,'Albania');
INSERT INTO paises (id,nombre) VALUES(4,'Alemania');
INSERT INTO paises (id,nombre) VALUES(5,'Andorra');
INSERT INTO paises (id,nombre) VALUES(6,'Angola');
INSERT INTO paises (id,nombre) VALUES(7,'Anguilla');
INSERT INTO paises (id,nombre) VALUES(8,'Antártida');
INSERT INTO paises (id,nombre) VALUES(9,'Antigua y Barbuda');
INSERT INTO paises (id,nombre) VALUES(10,'Antillas Holandesas');
INSERT INTO paises (id,nombre) VALUES(11,'Arabia Saudí');
INSERT INTO paises (id,nombre) VALUES(12,'Argelia');
INSERT INTO paises (id,nombre) VALUES(13,'Argentina');
INSERT INTO paises (id,nombre) VALUES(14,'Armenia');
INSERT INTO paises (id,nombre) VALUES(15,'Aruba');
INSERT INTO paises (id,nombre) VALUES(16,'Australia');
INSERT INTO paises (id,nombre) VALUES(17,'Austria');
INSERT INTO paises (id,nombre) VALUES(18,'Azerbaiyán');
INSERT INTO paises (id,nombre) VALUES(19,'Bahamas');
INSERT INTO paises (id,nombre) VALUES(20,'Bahréin');
INSERT INTO paises (id,nombre) VALUES(21,'Bangladesh');
INSERT INTO paises (id,nombre) VALUES(22,'Barbados');
INSERT INTO paises (id,nombre) VALUES(23,'Bielorrusia');
INSERT INTO paises (id,nombre) VALUES(24,'Bélgica');
INSERT INTO paises (id,nombre) VALUES(25,'Belice');
INSERT INTO paises (id,nombre) VALUES(26,'Benin');
INSERT INTO paises (id,nombre) VALUES(27,'Bermudas');
INSERT INTO paises (id,nombre) VALUES(28,'Bhután');
INSERT INTO paises (id,nombre) VALUES(29,'Bolivia');
INSERT INTO paises (id,nombre) VALUES(30,'Bosnia y Herzegovina');
INSERT INTO paises (id,nombre) VALUES(31,'Botsuana');
INSERT INTO paises (id,nombre) VALUES(32,'Isla Bouvet');
INSERT INTO paises (id,nombre) VALUES(33,'Brasil');
INSERT INTO paises (id,nombre) VALUES(34,'Brunéi');
INSERT INTO paises (id,nombre) VALUES(35,'Bulgaria');
INSERT INTO paises (id,nombre) VALUES(36,'Burkina Faso');
INSERT INTO paises (id,nombre) VALUES(37,'Burundi');
INSERT INTO paises (id,nombre) VALUES(38,'Cabo Verde');
INSERT INTO paises (id,nombre) VALUES(39,'Islas Caimán');
INSERT INTO paises (id,nombre) VALUES(40,'Camboya');
INSERT INTO paises (id,nombre) VALUES(41,'Camerún');
INSERT INTO paises (id,nombre) VALUES(42,'Canadá');
INSERT INTO paises (id,nombre) VALUES(43,'República Centroafricana');
INSERT INTO paises (id,nombre) VALUES(44,'Chad');
INSERT INTO paises (id,nombre) VALUES(45,'República Checa');
INSERT INTO paises (id,nombre) VALUES(46,'Chile');
INSERT INTO paises (id,nombre) VALUES(47,'China');
INSERT INTO paises (id,nombre) VALUES(48,'Chipre');
INSERT INTO paises (id,nombre) VALUES(49,'Isla de Navidad');
INSERT INTO paises (id,nombre) VALUES(50,'Ciudad del Vaticano');
INSERT INTO paises (id,nombre) VALUES(51,'Islas Cocos');
INSERT INTO paises (id,nombre) VALUES(52,'Colombia');
INSERT INTO paises (id,nombre) VALUES(53,'Comoras');
INSERT INTO paises (id,nombre) VALUES(54,'República Democrática del Congo');
INSERT INTO paises (id,nombre) VALUES(55,'Congo');
INSERT INTO paises (id,nombre) VALUES(56,'Islas Cook');
INSERT INTO paises (id,nombre) VALUES(57,'Corea del Norte');
INSERT INTO paises (id,nombre) VALUES(58,'Corea del Sur');
INSERT INTO paises (id,nombre) VALUES(59,'Costa de Marfil');
INSERT INTO paises (id,nombre) VALUES(60,'Costa Rica');
INSERT INTO paises (id,nombre) VALUES(61,'Croacia');
INSERT INTO paises (id,nombre) VALUES(62,'Cuba');
INSERT INTO paises (id,nombre) VALUES(63,'Dinamarca');
INSERT INTO paises (id,nombre) VALUES(64,'Dominica');
INSERT INTO paises (id,nombre) VALUES(65,'República Dominicana');
INSERT INTO paises (id,nombre) VALUES(66,'Ecuador');
INSERT INTO paises (id,nombre) VALUES(67,'Egipto');
INSERT INTO paises (id,nombre) VALUES(68,'El Salvador');
INSERT INTO paises (id,nombre) VALUES(69,'Emiratos Árabes Unidos');
INSERT INTO paises (id,nombre) VALUES(70,'Eritrea');
INSERT INTO paises (id,nombre) VALUES(71,'Eslovaquia');
INSERT INTO paises (id,nombre) VALUES(72,'Eslovenia');
INSERT INTO paises (id,nombre) VALUES(73,'España');
INSERT INTO paises (id,nombre) VALUES(74,'Islas ultramarinas de Estados Unidos');
INSERT INTO paises (id,nombre) VALUES(75,'Estados Unidos');
INSERT INTO paises (id,nombre) VALUES(76,'Estonia');
INSERT INTO paises (id,nombre) VALUES(77,'Etiopía');
INSERT INTO paises (id,nombre) VALUES(78,'Islas Feroe');
INSERT INTO paises (id,nombre) VALUES(79,'Filipinas');
INSERT INTO paises (id,nombre) VALUES(80,'Finlandia');
INSERT INTO paises (id,nombre) VALUES(81,'Fiyi');
INSERT INTO paises (id,nombre) VALUES(82,'Francia');
INSERT INTO paises (id,nombre) VALUES(83,'Gabón');
INSERT INTO paises (id,nombre) VALUES(84,'Gambia');
INSERT INTO paises (id,nombre) VALUES(85,'Georgia');
INSERT INTO paises (id,nombre) VALUES(86,'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO paises (id,nombre) VALUES(87,'Ghana');
INSERT INTO paises (id,nombre) VALUES(88,'Gibraltar');
INSERT INTO paises (id,nombre) VALUES(89,'Granada');
INSERT INTO paises (id,nombre) VALUES(90,'Grecia');
INSERT INTO paises (id,nombre) VALUES(91,'Groenlandia');
INSERT INTO paises (id,nombre) VALUES(92,'Guadalupe');
INSERT INTO paises (id,nombre) VALUES(93,'Guam');
INSERT INTO paises (id,nombre) VALUES(94,'Guatemala');
INSERT INTO paises (id,nombre) VALUES(95,'Guayana Francesa');
INSERT INTO paises (id,nombre) VALUES(96,'Guinea');
INSERT INTO paises (id,nombre) VALUES(97,'Guinea Ecuatorial');
INSERT INTO paises (id,nombre) VALUES(98,'Guinea-Bissau');
INSERT INTO paises (id,nombre) VALUES(99,'Guyana');
INSERT INTO paises (id,nombre) VALUES(100,'Haití');
INSERT INTO paises (id,nombre) VALUES(101,'Islas Heard y McDonald');
INSERT INTO paises (id,nombre) VALUES(102,'Honduras');
INSERT INTO paises (id,nombre) VALUES(103,'Hong Kong');
INSERT INTO paises (id,nombre) VALUES(104,'Hungría');
INSERT INTO paises (id,nombre) VALUES(105,'India');
INSERT INTO paises (id,nombre) VALUES(106,'Indonesia');
INSERT INTO paises (id,nombre) VALUES(107,'Irán');
INSERT INTO paises (id,nombre) VALUES(108,'Iraq');
INSERT INTO paises (id,nombre) VALUES(109,'Irlanda');
INSERT INTO paises (id,nombre) VALUES(110,'Islandia');
INSERT INTO paises (id,nombre) VALUES(111,'Israel');
INSERT INTO paises (id,nombre) VALUES(112,'Italia');
INSERT INTO paises (id,nombre) VALUES(113,'Jamaica');
INSERT INTO paises (id,nombre) VALUES(114,'Japón');
INSERT INTO paises (id,nombre) VALUES(115,'Jordania');
INSERT INTO paises (id,nombre) VALUES(116,'Kazajstán');
INSERT INTO paises (id,nombre) VALUES(117,'Kenia');
INSERT INTO paises (id,nombre) VALUES(118,'Kirguistán');
INSERT INTO paises (id,nombre) VALUES(119,'Kiribati');
INSERT INTO paises (id,nombre) VALUES(120,'Kuwait');
INSERT INTO paises (id,nombre) VALUES(121,'Laos');
INSERT INTO paises (id,nombre) VALUES(122,'Lesotho');
INSERT INTO paises (id,nombre) VALUES(123,'Letonia');
INSERT INTO paises (id,nombre) VALUES(124,'Líbano');
INSERT INTO paises (id,nombre) VALUES(125,'Liberia');
INSERT INTO paises (id,nombre) VALUES(126,'Libia');
INSERT INTO paises (id,nombre) VALUES(127,'Liechtenstein');
INSERT INTO paises (id,nombre) VALUES(128,'Lituania');
INSERT INTO paises (id,nombre) VALUES(129,'Luxemburgo');
INSERT INTO paises (id,nombre) VALUES(130,'Macao');
INSERT INTO paises (id,nombre) VALUES(131,'ARY Macedonia');
INSERT INTO paises (id,nombre) VALUES(132,'Madagascar');
INSERT INTO paises (id,nombre) VALUES(133,'Malasia');
INSERT INTO paises (id,nombre) VALUES(134,'Malawi');
INSERT INTO paises (id,nombre) VALUES(135,'Maldivas');
INSERT INTO paises (id,nombre) VALUES(136,'Malí');
INSERT INTO paises (id,nombre) VALUES(137,'Malta');
INSERT INTO paises (id,nombre) VALUES(138,'Islas Malvinas');
INSERT INTO paises (id,nombre) VALUES(139,'Islas Marianas del Norte');
INSERT INTO paises (id,nombre) VALUES(140,'Marruecos');
INSERT INTO paises (id,nombre) VALUES(141,'Islas Marshall');
INSERT INTO paises (id,nombre) VALUES(142,'Martinica');
INSERT INTO paises (id,nombre) VALUES(143,'Mauricio');
INSERT INTO paises (id,nombre) VALUES(144,'Mauritania');
INSERT INTO paises (id,nombre) VALUES(145,'Mayotte');
INSERT INTO paises (id,nombre) VALUES(146,'México');
INSERT INTO paises (id,nombre) VALUES(147,'Micronesia');
INSERT INTO paises (id,nombre) VALUES(148,'Moldavia');
INSERT INTO paises (id,nombre) VALUES(149,'Mónaco');
INSERT INTO paises (id,nombre) VALUES(150,'Mongolia');
INSERT INTO paises (id,nombre) VALUES(151,'Montserrat');
INSERT INTO paises (id,nombre) VALUES(152,'Mozambique');
INSERT INTO paises (id,nombre) VALUES(153,'Myanmar');
INSERT INTO paises (id,nombre) VALUES(154,'Namibia');
INSERT INTO paises (id,nombre) VALUES(155,'Nauru');
INSERT INTO paises (id,nombre) VALUES(156,'Nepal');
INSERT INTO paises (id,nombre) VALUES(157,'Nicaragua');
INSERT INTO paises (id,nombre) VALUES(158,'Níger');
INSERT INTO paises (id,nombre) VALUES(159,'Nigeria');
INSERT INTO paises (id,nombre) VALUES(160,'Niue');
INSERT INTO paises (id,nombre) VALUES(161,'Isla Norfolk');
INSERT INTO paises (id,nombre) VALUES(162,'Noruega');
INSERT INTO paises (id,nombre) VALUES(163,'Nueva Caledonia');
INSERT INTO paises (id,nombre) VALUES(164,'Nueva Zelanda');
INSERT INTO paises (id,nombre) VALUES(165,'Omán');
INSERT INTO paises (id,nombre) VALUES(166,'Países Bajos');
INSERT INTO paises (id,nombre) VALUES(167,'Pakistán');
INSERT INTO paises (id,nombre) VALUES(168,'Palau');
INSERT INTO paises (id,nombre) VALUES(169,'Palestina');
INSERT INTO paises (id,nombre) VALUES(170,'Panamá');
INSERT INTO paises (id,nombre) VALUES(171,'Papúa Nueva Guinea');
INSERT INTO paises (id,nombre) VALUES(172,'Paraguay');
INSERT INTO paises (id,nombre) VALUES(173,'Perú');
INSERT INTO paises (id,nombre) VALUES(174,'Islas Pitcairn');
INSERT INTO paises (id,nombre) VALUES(175,'Polinesia Francesa');
INSERT INTO paises (id,nombre) VALUES(176,'Polonia');
INSERT INTO paises (id,nombre) VALUES(177,'Portugal');
INSERT INTO paises (id,nombre) VALUES(178,'Puerto Rico');
INSERT INTO paises (id,nombre) VALUES(179,'Qatar');
INSERT INTO paises (id,nombre) VALUES(180,'Reino Unido');
INSERT INTO paises (id,nombre) VALUES(181,'Reunión');
INSERT INTO paises (id,nombre) VALUES(182,'Ruanda');
INSERT INTO paises (id,nombre) VALUES(183,'Rumania');
INSERT INTO paises (id,nombre) VALUES(184,'Rusia');
INSERT INTO paises (id,nombre) VALUES(185,'Sahara Occidental');
INSERT INTO paises (id,nombre) VALUES(186,'Islas Salomón');
INSERT INTO paises (id,nombre) VALUES(187,'Samoa');
INSERT INTO paises (id,nombre) VALUES(188,'Samoa Americana');
INSERT INTO paises (id,nombre) VALUES(189,'San Cristóbal y Nevis');
INSERT INTO paises (id,nombre) VALUES(190,'San Marino');
INSERT INTO paises (id,nombre) VALUES(191,'San Pedro y Miquelón');
INSERT INTO paises (id,nombre) VALUES(192,'San Vicente y las Granadinas');
INSERT INTO paises (id,nombre) VALUES(193,'Santa Helena');
INSERT INTO paises (id,nombre) VALUES(194,'Santa Lucía');
INSERT INTO paises (id,nombre) VALUES(195,'Santo Tomé y Príncipe');
INSERT INTO paises (id,nombre) VALUES(196,'Senegal');
INSERT INTO paises (id,nombre) VALUES(197,'Serbia y Montenegro');
INSERT INTO paises (id,nombre) VALUES(198,'Seychelles');
INSERT INTO paises (id,nombre) VALUES(199,'Sierra Leona');
INSERT INTO paises (id,nombre) VALUES(200,'Singapur');
INSERT INTO paises (id,nombre) VALUES(201,'Siria');
INSERT INTO paises (id,nombre) VALUES(202,'Somalia');
INSERT INTO paises (id,nombre) VALUES(203,'Sri Lanka');
INSERT INTO paises (id,nombre) VALUES(204,'Suazilandia');
INSERT INTO paises (id,nombre) VALUES(205,'Sudáfrica');
INSERT INTO paises (id,nombre) VALUES(206,'Sudán');
INSERT INTO paises (id,nombre) VALUES(207,'Suecia');
INSERT INTO paises (id,nombre) VALUES(208,'Suiza');
INSERT INTO paises (id,nombre) VALUES(209,'Surinam');
INSERT INTO paises (id,nombre) VALUES(210,'Svalbard y Jan Mayen');
INSERT INTO paises (id,nombre) VALUES(211,'Tailandia');
INSERT INTO paises (id,nombre) VALUES(212,'Taiwán');
INSERT INTO paises (id,nombre) VALUES(213,'Tanzania');
INSERT INTO paises (id,nombre) VALUES(214,'Tayikistán');
INSERT INTO paises (id,nombre) VALUES(215,'Territorio Británico del Océano Índico');
INSERT INTO paises (id,nombre) VALUES(216,'Territorios Australes Franceses');
INSERT INTO paises (id,nombre) VALUES(217,'Timor Oriental');
INSERT INTO paises (id,nombre) VALUES(218,'Togo');
INSERT INTO paises (id,nombre) VALUES(219,'Tokelau');
INSERT INTO paises (id,nombre) VALUES(220,'Tonga');
INSERT INTO paises (id,nombre) VALUES(221,'Trinidad y Tobago');
INSERT INTO paises (id,nombre) VALUES(222,'Túnez');
INSERT INTO paises (id,nombre) VALUES(223,'Islas Turcas y Caicos');
INSERT INTO paises (id,nombre) VALUES(224,'Turkmenistán');
INSERT INTO paises (id,nombre) VALUES(225,'Turquía');
INSERT INTO paises (id,nombre) VALUES(226,'Tuvalu');
INSERT INTO paises (id,nombre) VALUES(227,'Ucrania');
INSERT INTO paises (id,nombre) VALUES(228,'Uganda');
INSERT INTO paises (id,nombre) VALUES(229,'Uruguay');
INSERT INTO paises (id,nombre) VALUES(230,'Uzbekistán');
INSERT INTO paises (id,nombre) VALUES(231,'Vanuatu');
INSERT INTO paises (id,nombre) VALUES(232,'Venezuela');
INSERT INTO paises (id,nombre) VALUES(233,'Vietnam');
INSERT INTO paises (id,nombre) VALUES(234,'Islas Vírgenes Británicas');
INSERT INTO paises (id,nombre) VALUES(235,'Islas Vírgenes de los Estados Unidos');
INSERT INTO paises (id,nombre) VALUES(236,'Wallis y Futuna');
INSERT INTO paises (id,nombre) VALUES(237,'Yemen');
INSERT INTO paises (id,nombre) VALUES(238,'Yibuti');
INSERT INTO paises (id,nombre) VALUES(239,'Zambia');
INSERT INTO paises (id,nombre) VALUES(240,'Zimbabue');